### PR TITLE
Added support for multi field searching

### PR DESCRIPTION
**Pull request by csteele86**
I've added support for multi field searching. See the "Custom Multi Field Search" section here: https://developer.nutritionix.com/docs/v1_1. 

Please let me know if there are any changes you would like me to make!

### CODE REVIEW

**Comment by carolynvs** [comment]
This looks really good! Ignore the travis build, it's all messed up from when I tried to move this over to .net core. I'll give this a compile tomorrow and merge if it passes. Thanks!

**Comment by csteele86** [comment]
Sounds great! Will you be updating the Nuget package as well?

**Comment by carolynvs** [comment]
Yup, I'll publish back to Nuget after merging. I'll ping back here when it's ready to download.

**Comment by csteele86** [comment]
Thank you!

**Comment by carolynvs** [comment]
Please give this a try and reopen this issue if the package doesn't work. Thanks for the PR!

https://www.nuget.org/packages/Nutritionix/1.3.1

**Pull request merged**
